services:
  github-stats:
    image: golang:1.25
    container_name: github-stats-server
    restart: always
    ports:
      - "127.0.0.1:8063:8063"
    command: bash -c "go mod download && go run ."
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
